import { Alert } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import * as ImageManipulator from 'expo-image-manipulator';

/**
 * Image capture + compress helpers for the A1 photo/camera send lane.
 *
 * Lifted from altum-phone `src/components/Capture.tsx` (which in turn lifted
 * tax-tabby's expo-image-picker + expo-image-manipulator pipeline). Adapted to
 * pentacle: the 5-image cap (D2) is enforced by the CALLER (the composer) via
 * `selectionLimit`; HEIC→JPEG + compress (D2) runs here before upload. The iOS
 * usage strings (`NSCameraUsageDescription`/`NSPhotoLibraryUsageDescription`)
 * are generated by the expo-image-picker config plugin in `app.config.ts`
 * (managed Expo / CNG — there is no checked-in Info.plist).
 */

export interface ProcessedAsset {
  uri: string;
  fileName: string;
  mimeType: string;
  width: number | null;
  height: number | null;
  // Byte size of the compressed JPEG, measured during `compressForUpload`.
  // Feeds `ChatAttachment.bytes` + the mint request's optional `bytes` hint.
  bytes: number;
}

// iPhone photos arrive as multi-MB HEIC/JPEG. Resize the longest edge down and
// re-encode as JPEG so every attachment lands comfortably under the upload
// ceiling before the daemon blob RPC. Mirror altum's 4 MB ceiling + single retry
// discipline.
const MAX_EDGE = 2000;
const JPEG_QUALITY = 0.7;
// Hard app-side ceiling on the compressed byte size. The first pass targets
// MAX_EDGE @ JPEG_QUALITY; if the result still exceeds this we retry once at a
// smaller edge + lower quality, and if it is *still* over we throw so the caller
// aborts the send (no upload) and surfaces the failure UI.
const MAX_UPLOAD_BYTES = 4 * 1024 * 1024;
const RETRY_MAX_EDGE = 1280;
const RETRY_JPEG_QUALITY = 0.5;

/** Raised when a compressed image cannot be brought under the size ceiling. */
export class MediaTooLargeError extends Error {
  readonly bytes: number;
  constructor(bytes: number) {
    super(
      `Compressed image is ${bytes} bytes, over the ${MAX_UPLOAD_BYTES}-byte upload ceiling`,
    );
    this.name = 'MediaTooLargeError';
    this.bytes = bytes;
  }
}

// Byte size of a base64 payload (the manipulator's `base64` output) without
// allocating the decoded buffer: 4 base64 chars encode 3 bytes, minus padding.
// Returns 0 when base64 is absent so the guard degrades to a no-op rather than
// blocking a send on a missing measurement.
function base64ByteLength(base64?: string | null): number {
  if (!base64) return 0;
  const padding = base64.endsWith('==') ? 2 : base64.endsWith('=') ? 1 : 0;
  return Math.floor((base64.length * 3) / 4) - padding;
}

function toProcessed(asset: ImagePicker.ImagePickerAsset): ProcessedAsset {
  const baseName = (asset.fileName || `chat-image`).replace(/\.[^.]+$/, '');
  return {
    uri: asset.uri,
    fileName: `${baseName}.jpg`,
    mimeType: 'image/jpeg',
    width: asset.width ?? null,
    height: asset.height ?? null,
    bytes: 0,
  };
}

interface ManipulatedImage {
  uri: string;
  width: number | null;
  height: number | null;
  bytes: number;
}

// Resize (longest edge → maxEdge, preserving aspect) + JPEG re-encode at the
// given quality, returning the result plus its measured byte size.
async function manipulateToJpeg(
  asset: ProcessedAsset,
  maxEdge: number,
  quality: number,
): Promise<ManipulatedImage> {
  const longest = Math.max(asset.width ?? 0, asset.height ?? 0);
  const actions: ImageManipulator.Action[] = [];
  if (longest > maxEdge) {
    // Constrain whichever edge is longer; the manipulator preserves aspect.
    if ((asset.width ?? 0) >= (asset.height ?? 0)) {
      actions.push({ resize: { width: maxEdge } });
    } else {
      actions.push({ resize: { height: maxEdge } });
    }
  }
  const result = await ImageManipulator.manipulateAsync(asset.uri, actions, {
    compress: quality,
    format: ImageManipulator.SaveFormat.JPEG,
    base64: true,
  });
  return {
    uri: result.uri,
    width: result.width ?? asset.width ?? null,
    height: result.height ?? asset.height ?? null,
    bytes: base64ByteLength(result.base64),
  };
}

/**
 * Resize + re-encode an asset to JPEG (HEIC→JPEG, D2) so it is comfortably under
 * the upload size ceiling. Retries once at a smaller edge + lower quality if the
 * first pass exceeds {@link MAX_UPLOAD_BYTES}; throws {@link MediaTooLargeError}
 * if it still cannot fit, so the caller aborts the send without uploading.
 * Returns the manipulated uri, post-resize dimensions, and measured byte size.
 */
export async function compressForUpload(
  asset: ProcessedAsset,
): Promise<ProcessedAsset> {
  let out = await manipulateToJpeg(asset, MAX_EDGE, JPEG_QUALITY);
  if (out.bytes > MAX_UPLOAD_BYTES) {
    out = await manipulateToJpeg(asset, RETRY_MAX_EDGE, RETRY_JPEG_QUALITY);
    if (out.bytes > MAX_UPLOAD_BYTES) {
      throw new MediaTooLargeError(out.bytes);
    }
  }
  return {
    uri: out.uri,
    fileName: asset.fileName,
    mimeType: 'image/jpeg',
    width: out.width,
    height: out.height,
    bytes: out.bytes,
  };
}

/**
 * Pick one or more images from the library (multi-select). The caller passes a
 * dynamic `selectionLimit` (the remaining slots under the 5-image cap, D2) so a
 * pick can never overshoot the cap. Returns the selected assets (empty on
 * deny/cancel), sliced to `selectionLimit` as belt-and-braces. The assets are
 * NOT yet compressed — the caller runs `compressForUpload` per asset.
 */
export async function pickImagesFromLibrary(
  selectionLimit: number,
): Promise<ProcessedAsset[]> {
  if (selectionLimit <= 0) return [];
  const permission = await ImagePicker.requestMediaLibraryPermissionsAsync();
  if (!permission.granted) {
    Alert.alert('Photo access needed', 'Allow photo library access to attach photos.');
    return [];
  }
  const result = await ImagePicker.launchImageLibraryAsync({
    mediaTypes: ['images'],
    allowsMultipleSelection: true,
    selectionLimit,
    quality: 0.9,
  });
  if (result.canceled || !result.assets?.length) return [];
  return result.assets.slice(0, selectionLimit).map(toProcessed);
}

/** Capture a single photo with the camera. Returns null on deny/cancel. */
export async function captureImageFromCamera(): Promise<ProcessedAsset | null> {
  const permission = await ImagePicker.requestCameraPermissionsAsync();
  if (!permission.granted) {
    Alert.alert('Camera access needed', 'Allow camera access to take a photo.');
    return null;
  }
  const result = await ImagePicker.launchCameraAsync({
    mediaTypes: ['images'],
    quality: 0.9,
  });
  if (result.canceled || !result.assets?.[0]) return null;
  return toProcessed(result.assets[0]);
}
