const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const scenePlugin = require('../plugins/withSceneLifecycle');
const harnessPlugin = require('../plugins/withHarnessLaunchUrl');

const template = `import Expo
import React
import ReactAppDependencyProvider
@UIApplicationMain
public class AppDelegate: ExpoAppDelegate {
  var window: UIWindow?
  var reactNativeDelegate: ExpoReactNativeFactoryDelegate?
  var reactNativeFactory: RCTReactNativeFactory?
  public override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
  ) -> Bool {
    let delegate = ReactNativeDelegate()
    let factory = ExpoReactNativeFactory(delegate: delegate)
    delegate.dependencyProvider = RCTAppDependencyProvider()
    reactNativeDelegate = delegate
    reactNativeFactory = factory
    bindReactNativeFactory(factory)
#if os(iOS) || os(tvOS)
    window = UIWindow(frame: UIScreen.main.bounds)
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)
#endif
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
  // Existing application link overrides and push subscribers are preserved.
}
`;

test('preserves harness launch options and factory binding while moving startup to the scene', () => {
  const withHarness = harnessPlugin.patchAppDelegate(template);
  const patched = scenePlugin.patchAppDelegate(withHarness);
  expect(patched).toContain('bindReactNativeFactory(factory)');
  expect(patched).toContain('sceneLaunchOptions = effectiveLaunchOptions');
  expect(patched).toContain('didFinishLaunchingWithOptions: effectiveLaunchOptions');
  expect(patched).toContain('PENTACLE_GATE_READY_NONCE');
  expect(patched).toContain('Existing application link overrides and push subscribers are preserved.');
  expect(patched.slice(0, patched.indexOf('// Generated by withSceneLifecycle'))).not.toContain('factory.startReactNative(');
  expect(scenePlugin.patchAppDelegate(patched)).toBe(patched);
  expect(harnessPlugin.patchAppDelegate(patched)).toBe(patched);
});

test('declares one scene without changing unrelated security or application settings', () => {
  const original = { NSFaceIDUsageDescription: 'Protected access', arbitrary: { keep: true } };
  const result = scenePlugin.patchInfoPlist(original);
  expect(result).toEqual({ ...original, UIApplicationSceneManifest: scenePlugin.SCENE_MANIFEST });
  expect(original).not.toHaveProperty('UIApplicationSceneManifest');
  expect(scenePlugin.patchInfoPlist(result)).toEqual(result);
  const parsed = require('@expo/plist').default.parse(require('@expo/plist').default.build(result));
  expect(scenePlugin.patchInfoPlist(parsed)).toEqual(result);
  expect(() => scenePlugin.patchInfoPlist({ UIApplicationSceneManifest: { UIApplicationSupportsMultipleScenes: true } })).toThrow('SCENE_LIFECYCLE_MANIFEST');
});

test.each(['', template, harnessPlugin.patchAppDelegate(template).repeat(2)])('refuses unknown or ambiguous templates', source => {
  expect(() => scenePlugin.patchAppDelegate(source)).toThrow('SCENE_LIFECYCLE_TEMPLATE');
});

test('runs after the unchanged harness AppDelegate mod in Expo reverse registration order', () => {
  const config = fs.readFileSync(path.join(__dirname, '../app.config.ts'), 'utf8');
  expect(config.indexOf("'./plugins/withSceneLifecycle'")).toBeLessThan(config.indexOf("'./plugins/withHarnessLaunchUrl'"));
});

// UIKit compilation is proved by the simulator build. This host test executes
// the generated Swift and real locked Expo notification manager/emitter with
// explicit platform/factory/serialization boundaries, including a cold replay.
(process.platform === 'darwin' ? test : test.skip)('native scene behavior and Expo cold notification delivery', () => {
  const result = spawnSync(process.execPath, [path.join(__dirname, '../scripts/test-scene-lifecycle-native.cjs')], {
    encoding: 'utf8', timeout: 90000,
  });
  expect({ status: result.status, error: result.error, output: result.stdout + result.stderr }).toEqual({
    status: 0, error: undefined, output: expect.stringContaining('SCENE_NATIVE_PASS'),
  });
}, 100000);
