import Expo
import React
import ReactAppDependencyProvider

@UIApplicationMain
public class AppDelegate: ExpoAppDelegate {
  var window: UIWindow?

  var reactNativeDelegate: ExpoReactNativeFactoryDelegate?
  var reactNativeFactory: RCTReactNativeFactory?
  var sceneLaunchOptions: [UIApplication.LaunchOptionsKey: Any]?

  private func launchOptionsWithHarnessURL(
    _ launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> [UIApplication.LaunchOptionsKey: Any]? {
#if targetEnvironment(simulator)
    let environment = ProcessInfo.processInfo.environment
    let arguments = ProcessInfo.processInfo.arguments
    let markers = arguments.indices.filter { arguments[$0] == "-HarnessUrl" }
    if environment["PENTACLE_ALLOW_HARNESS_LAUNCH_ARG"] == "1",
       markers.count == 1,
       arguments.indices.contains(markers[0] + 1),
       let url = URL(string: arguments[markers[0] + 1]),
       url.scheme == "pentacle",
       url.host == "harness" {
      var effective = launchOptions ?? [:]
      var effectiveURL = url
      let tokenMarkers = arguments.indices.filter { arguments[$0] == "-PentacleDeviceToken" }
      if tokenMarkers.count == 1,
         arguments.indices.contains(tokenMarkers[0] + 1),
         var components = URLComponents(url: url, resolvingAgainstBaseURL: false) {
        var items = components.queryItems ?? []
        items.append(URLQueryItem(name: "install_device_token", value: arguments[tokenMarkers[0] + 1]))
        components.queryItems = items
        if let merged = components.url { effectiveURL = merged }
      }
      effective[.url] = effectiveURL
      return effective
    }
#endif
    return launchOptions
  }

  public override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
  ) -> Bool {
    let effectiveLaunchOptions = launchOptionsWithHarnessURL(launchOptions)
#if targetEnvironment(simulator)
    if let nonce = ProcessInfo.processInfo.environment["PENTACLE_GATE_READY_NONCE"], !nonce.isEmpty {
      NotificationCenter.default.addObserver(forName: NSNotification.Name("RCTContentDidAppearNotification"), object: nil, queue: .main) { _ in
        let receipt: [String: Any] = ["nonce": nonce, "bundle_id": Bundle.main.bundleIdentifier ?? "", "pid": ProcessInfo.processInfo.processIdentifier, "created_at": Date().timeIntervalSince1970 * 1000]
        if let directory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first,
           let data = try? JSONSerialization.data(withJSONObject: receipt) {
          try? data.write(to: directory.appendingPathComponent(".pentacle-gate-ready.json"), options: .atomic)
        }
      }
    }
#endif
    let delegate = ReactNativeDelegate()
    let factory = ExpoReactNativeFactory(delegate: delegate)
    delegate.dependencyProvider = RCTAppDependencyProvider()

    reactNativeDelegate = delegate
    reactNativeFactory = factory
    bindReactNativeFactory(factory)

    sceneLaunchOptions = effectiveLaunchOptions

    return super.application(application, didFinishLaunchingWithOptions: effectiveLaunchOptions)
  }

  // Linking API
  public override func application(
    _ app: UIApplication,
    open url: URL,
    options: [UIApplication.OpenURLOptionsKey: Any] = [:]
  ) -> Bool {
    return super.application(app, open: url, options: options) || RCTLinkingManager.application(app, open: url, options: options)
  }

  // Universal Links
  public override func application(
    _ application: UIApplication,
    continue userActivity: NSUserActivity,
    restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void
  ) -> Bool {
    let result = RCTLinkingManager.application(application, continue: userActivity, restorationHandler: restorationHandler)
    return super.application(application, continue: userActivity, restorationHandler: restorationHandler) || result
  }
}

class ReactNativeDelegate: ExpoReactNativeFactoryDelegate {
  // Extension point for config-plugins

  override func sourceURL(for bridge: RCTBridge) -> URL? {
#if PENTACLE_E2E_EMBEDDED_BUNDLE
    bundleURL()
#else
    bridge.bundleURL ?? bundleURL()
#endif
  }

  override func bundleURL() -> URL? {
#if PENTACLE_E2E_EMBEDDED_BUNDLE
    return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#elseif DEBUG
    return RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: ".expo/.virtual-metro-entry")
#else
    return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }
}

// Generated by withSceneLifecycle (SDK 54).
@objc(PentacleSceneDelegate)
class PentacleSceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  private var appDelegate: AppDelegate? {
    UIApplication.shared.delegate as? AppDelegate
  }

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene else { return }
    guard let appDelegate, let factory = appDelegate.reactNativeFactory else {
      fatalError("Pentacle scene requires the bound Expo React Native factory")
    }

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    // RN 0.81 and Expo modules still consult the application delegate's window.
    let previousWindow = appDelegate.window
    appDelegate.window = window
    if let root = previousWindow?.rootViewController {
      previousWindow?.rootViewController = nil
      window.rootViewController = root
    } else {
      factory.startReactNative(
        withModuleName: "main",
        in: window,
        launchOptions: Self.launchOptions(appDelegate.sceneLaunchOptions, connectionOptions))
    }
    window.makeKeyAndVisible()

    // Use the existing Expo/RCTLinkingManager overrides once per incoming item.
    self.scene(scene, openURLContexts: connectionOptions.urlContexts)
    connectionOptions.userActivities.forEach { self.scene(scene, continue: $0) }
    // UIKit delivers notification responses to the existing UN notification
    // center delegate. Dispatching them here too would duplicate Expo events.
    NSLog("[PentacleScene] bug_ref=ios27_scene_lifecycle event=connected")
  }

  static func launchOptions(
    _ original: [UIApplication.LaunchOptionsKey: Any]?,
    _ connection: UIScene.ConnectionOptions
  ) -> [UIApplication.LaunchOptionsKey: Any]? {
    var options = original ?? [:]
    if let url = connection.urlContexts.first?.url {
      options[UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsURLKey")] = url
    }
    if let activity = connection.userActivities.first(where: { $0.activityType == NSUserActivityTypeBrowsingWeb }) {
      options[UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsUserActivityDictionaryKey")] = [
        "UIApplicationLaunchOptionsUserActivityTypeKey": activity.activityType,
        "UIApplicationLaunchOptionsUserActivityKey": activity
      ]
    }
    if let response = connection.notificationResponse {
      options[UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsRemoteNotificationKey")] = response.notification.request.content.userInfo
    }
    return options.isEmpty ? nil : options
  }

  func scene(_ scene: UIScene, openURLContexts contexts: Set<UIOpenURLContext>) {
    for context in contexts {
      var options: [UIApplication.OpenURLOptionsKey: Any] = [.openInPlace: context.options.openInPlace]
      if let source = context.options.sourceApplication { options[.sourceApplication] = source }
      if let annotation = context.options.annotation { options[.annotation] = annotation }
      _ = appDelegate?.application(UIApplication.shared, open: context.url, options: options)
    }
  }

  func scene(_ scene: UIScene, continue activity: NSUserActivity) {
    _ = appDelegate?.application(UIApplication.shared, continue: activity, restorationHandler: { _ in })
  }

  func sceneDidBecomeActive(_ scene: UIScene) {
    appDelegate?.applicationDidBecomeActive(UIApplication.shared)
  }

  func sceneWillResignActive(_ scene: UIScene) {
    appDelegate?.applicationWillResignActive(UIApplication.shared)
  }

  func sceneWillEnterForeground(_ scene: UIScene) {
    appDelegate?.applicationWillEnterForeground(UIApplication.shared)
  }

  func sceneDidEnterBackground(_ scene: UIScene) {
    appDelegate?.applicationDidEnterBackground(UIApplication.shared)
  }

  func sceneDidDisconnect(_ scene: UIScene) {
    // Keep the application delegate's root for a single-scene reconnection.
    window = nil
  }
}
