// SDK 54 adapter for the public ExpoReactNativeFactory API. SDK 57's
// enableSceneSupport cannot be used with this app's lock-resolved Expo version.
const SCENE_DELEGATE = `
// Generated by withSceneLifecycle (SDK 54).
@objc(PentacleSceneDelegate)
class PentacleSceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  private var appDelegate: AppDelegate? {
    UIApplication.shared.delegate as? AppDelegate
  }

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene else { return }
    guard let appDelegate, let factory = appDelegate.reactNativeFactory else {
      fatalError("Pentacle scene requires the bound Expo React Native factory")
    }

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    // RN 0.81 and Expo modules still consult the application delegate's window.
    let previousWindow = appDelegate.window
    appDelegate.window = window
    if let root = previousWindow?.rootViewController {
      previousWindow?.rootViewController = nil
      window.rootViewController = root
    } else {
      factory.startReactNative(
        withModuleName: "main",
        in: window,
        launchOptions: Self.launchOptions(appDelegate.sceneLaunchOptions, connectionOptions))
    }
    window.makeKeyAndVisible()

    // Use the existing Expo/RCTLinkingManager overrides once per incoming item.
    self.scene(scene, openURLContexts: connectionOptions.urlContexts)
    connectionOptions.userActivities.forEach { self.scene(scene, continue: $0) }
    // UIKit delivers notification responses to the existing UN notification
    // center delegate. Dispatching them here too would duplicate Expo events.
    NSLog("[PentacleScene] bug_ref=ios27_scene_lifecycle event=connected")
  }

  static func launchOptions(
    _ original: [UIApplication.LaunchOptionsKey: Any]?,
    _ connection: UIScene.ConnectionOptions
  ) -> [UIApplication.LaunchOptionsKey: Any]? {
    var options = original ?? [:]
    if let url = connection.urlContexts.first?.url {
      options[UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsURLKey")] = url
    }
    if let activity = connection.userActivities.first(where: { $0.activityType == NSUserActivityTypeBrowsingWeb }) {
      options[UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsUserActivityDictionaryKey")] = [
        "UIApplicationLaunchOptionsUserActivityTypeKey": activity.activityType,
        "UIApplicationLaunchOptionsUserActivityKey": activity
      ]
    }
    if let response = connection.notificationResponse {
      options[UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsRemoteNotificationKey")] = response.notification.request.content.userInfo
    }
    return options.isEmpty ? nil : options
  }

  func scene(_ scene: UIScene, openURLContexts contexts: Set<UIOpenURLContext>) {
    for context in contexts {
      var options: [UIApplication.OpenURLOptionsKey: Any] = [.openInPlace: context.options.openInPlace]
      if let source = context.options.sourceApplication { options[.sourceApplication] = source }
      if let annotation = context.options.annotation { options[.annotation] = annotation }
      _ = appDelegate?.application(UIApplication.shared, open: context.url, options: options)
    }
  }

  func scene(_ scene: UIScene, continue activity: NSUserActivity) {
    _ = appDelegate?.application(UIApplication.shared, continue: activity, restorationHandler: { _ in })
  }

  func sceneDidBecomeActive(_ scene: UIScene) {
    appDelegate?.applicationDidBecomeActive(UIApplication.shared)
  }

  func sceneWillResignActive(_ scene: UIScene) {
    appDelegate?.applicationWillResignActive(UIApplication.shared)
  }

  func sceneWillEnterForeground(_ scene: UIScene) {
    appDelegate?.applicationWillEnterForeground(UIApplication.shared)
  }

  func sceneDidEnterBackground(_ scene: UIScene) {
    appDelegate?.applicationDidEnterBackground(UIApplication.shared)
  }

  func sceneDidDisconnect(_ scene: UIScene) {
    // Keep the application delegate's root for a single-scene reconnection.
    window = nil
  }
}
`;

const SCENE_MANIFEST = {
  UIApplicationSupportsMultipleScenes: false,
  UISceneConfigurations: {
    UIWindowSceneSessionRoleApplication: [{
      UISceneConfigurationName: 'Default Configuration',
      UISceneDelegateClassName: 'PentacleSceneDelegate',
    }],
  },
};

function replaceOnce(source, needle, replacement) {
  if (!source.includes(needle) || source.indexOf(needle) !== source.lastIndexOf(needle)) {
    throw new Error('SCENE_LIFECYCLE_TEMPLATE: expected one SDK 54 startup block');
  }
  return source.replace(needle, replacement);
}

function patchAppDelegate(source) {
  if (source.includes('// Generated by withSceneLifecycle')) {
    if (!source.endsWith(SCENE_DELEGATE) || !source.includes('    sceneLaunchOptions = effectiveLaunchOptions')) {
      throw new Error('SCENE_LIFECYCLE_TEMPLATE: edited scene integration');
    }
    return source;
  }
  if (!source.includes('public class AppDelegate: ExpoAppDelegate {')
    || !source.includes('    bindReactNativeFactory(factory)')
    || !source.includes('let effectiveLaunchOptions = launchOptionsWithHarnessURL(launchOptions)')) {
    throw new Error('SCENE_LIFECYCLE_TEMPLATE: requires SDK 54 and withHarnessLaunchUrl before this mod');
  }
  let patched = replaceOnce(source, '  var reactNativeFactory: RCTReactNativeFactory?',
    '  var reactNativeFactory: RCTReactNativeFactory?\n  var sceneLaunchOptions: [UIApplication.LaunchOptionsKey: Any]?');
  const startup = `#if os(iOS) || os(tvOS)
    window = UIWindow(frame: UIScreen.main.bounds)
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: effectiveLaunchOptions)
#endif`;
  patched = replaceOnce(patched, startup, '    sceneLaunchOptions = effectiveLaunchOptions');
  return patched + SCENE_DELEGATE;
}

function patchInfoPlist(info) {
  if (info.UIApplicationSceneManifest
    // Expo's plist reader uses null-prototype dictionaries. Compare plist
    // values, rather than rejecting the generated dictionary's prototype.
    && !require('node:util').isDeepStrictEqual(
      JSON.parse(JSON.stringify(info.UIApplicationSceneManifest)), SCENE_MANIFEST)) {
    throw new Error('SCENE_LIFECYCLE_MANIFEST: refusing a different scene configuration');
  }
  return { ...info, UIApplicationSceneManifest: JSON.parse(JSON.stringify(SCENE_MANIFEST)) };
}

function withSceneLifecycle(config) {
  if (!require('expo/package.json').version.startsWith('54.')) {
    throw new Error('SCENE_LIFECYCLE_SDK: replace this adapter when upgrading Expo');
  }
  const { withAppDelegate, withInfoPlist } = require('@expo/config-plugins');
  const delegate = withAppDelegate(config, mod => {
    if (mod.modResults.language !== 'swift') throw new Error('SCENE_LIFECYCLE_TEMPLATE: Swift required');
    mod.modResults.contents = patchAppDelegate(mod.modResults.contents);
    return mod;
  });
  return withInfoPlist(delegate, mod => {
    mod.modResults = patchInfoPlist(mod.modResults);
    return mod;
  });
}

module.exports = withSceneLifecycle;
module.exports.patchAppDelegate = patchAppDelegate;
module.exports.patchInfoPlist = patchInfoPlist;
module.exports.SCENE_DELEGATE = SCENE_DELEGATE;
module.exports.SCENE_MANIFEST = SCENE_MANIFEST;
