"""Waiver YAML loader + markdown table renderer.

Single source of truth: ``test/e2e/waivers.yaml`` (parsed directly by the
e2e runner). The ``## Waivers`` section in ``docs/E2E_HARNESS.md`` is
autogenerated from the YAML via :func:`render_waivers_md` for the
``bin/pentacle-walk render-waivers-md`` subcommand.

Spec: spec_pentacle_mobile_e2e_telemetry_flows_2026_05_13 Stage 1.3.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_WAIVERS_PATH = REPO_ROOT / "test" / "e2e" / "waivers.yaml"

TABLE_HEADER = "| Scenario id | Reason | Tracking spec | Granted on | Expires on |"
TABLE_SEPARATOR = "|---|---|---|---|---|"
REQUIRED_FIELDS = ("scenario_id", "reason", "tracking_spec", "granted_on", "expires_on")


def load_waivers(path: str | Path | None = None) -> list[dict[str, Any]]:
    """Load and minimally validate the waivers YAML.

    Returns the list of waiver dicts (may be empty). Raises ``ValueError``
    if the file shape is unexpected.
    """
    target = Path(path) if path else DEFAULT_WAIVERS_PATH
    raw = yaml.safe_load(target.read_text(encoding="utf-8")) or {}
    if not isinstance(raw, dict):
        raise ValueError(f"{target}: top-level YAML must be a mapping")
    waivers = raw.get("waivers", [])
    if waivers is None:
        return []
    if not isinstance(waivers, list):
        raise ValueError(f"{target}: 'waivers' must be a list")
    for idx, entry in enumerate(waivers):
        if not isinstance(entry, dict):
            raise ValueError(f"{target}: waivers[{idx}] must be a mapping")
        for required in REQUIRED_FIELDS:
            if required not in entry:
                raise ValueError(f"{target}: waivers[{idx}] missing field '{required}'")
    return waivers


def render_waivers_md(path: str | Path | None = None) -> str:
    """Render the waivers YAML as a markdown table with a trailing newline."""
    waivers = load_waivers(path)
    lines = [TABLE_HEADER, TABLE_SEPARATOR]
    for entry in waivers:
        cells = [
            f"`{entry['scenario_id']}`",
            f"`{entry['reason']}`",
            f"`{entry['tracking_spec']}`",
            f"`{entry['granted_on']}`",
            f"`{entry['expires_on']}`",
        ]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint for ``bin/pentacle-walk render-waivers-md``.

    Reads ``test/e2e/waivers.yaml`` and prints the markdown table to stdout.
    """
    import argparse
    import sys

    parser = argparse.ArgumentParser(description="Render waivers.yaml as a markdown table.")
    parser.add_argument(
        "--path",
        default=None,
        help="path to waivers.yaml (default: test/e2e/waivers.yaml relative to repo root)",
    )
    args = parser.parse_args(argv if argv is not None else sys.argv[1:])
    sys.stdout.write(render_waivers_md(args.path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
